name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Library
      run: dotnet build --configuration Release ./AndroidSdk/AndroidSdk.csproj
    - name: Build Tool
      run: dotnet build --configuration Release ./AndroidSdk.Tool/AndroidSdk.Tool.csproj
    - name: Build Tests
      run: dotnet build --configuration Release ./AndroidSdk.Tests/AndroidSdk.Tests.csproj
