name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Library
      run: dotnet build --configuration Release ./Android.Tools/Android.Tools.csproj
    - name: Build Runner
      run: dotnet build --configuration Release ./Android.Tools.Runner/Android.Tools.Runner.csproj
    - name: Build Tests
      run: dotnet build --configuration Release ./Android.Tools.Tests/Android.Tools.Tests.csproj
